spring.datasource.url=jdbc:mysql://10.0.157.1:3306/zonix
spring.datasource.username=mc
spring.datasource.password=ZwPZeFD5pb8wCUUX
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=2583
