# Generated by Django 2.0 on 2018-01-13 02:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('uid', models.UUIDField(default=uuid.UUID('1ec2863d-b42c-445d-bf96-e2b2c4c1771d'))),
                ('join_date', models.DateTimeField(default=datetime.datetime(2018, 1, 12, 21, 25, 54, 150190), verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteUserBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=400)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2018, 1, 12, 21, 25, 54, 150691), verbose_name='date expired')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(default=uuid.UUID('57a279d1-3135-4291-8952-590107ddefee'))),
                ('log', models.TextField()),
                ('ip_address', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 1, 12, 21, 25, 54, 151192), verbose_name='log created')),
            ],
        ),
    ]
