# Generated by Django 2.0 on 2018-01-13 02:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180112_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 21, 26, 28, 750884), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4ebd1a24-7eb0-4b3b-aaf1-3d7877d13c99')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 21, 26, 28, 751386), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 21, 26, 28, 751386), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('090b4973-de1d-4644-a08a-715ad58ebea1')),
        ),
    ]
