# Generated by Django 2.0 on 2018-01-23 19:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180123_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 40, 13, 553902), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b768d35f-973f-42de-a029-2468e864a7fe')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 40, 13, 554905), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 14, 40, 13, 555406), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('0323e77d-2277-4e0c-a352-0cc186fa8ea1')),
        ),
    ]
