# Generated by Django 2.0.2 on 2018-02-09 18:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20180208_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(default=uuid.UUID('c127eb44-517f-4899-bbd0-14abaabfb18e'))),
                ('message', models.TextField()),
                ('link', models.TextField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 13, 42, 18, 783117), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('394b4590-baf6-47ff-bbc8-3029c190ed51')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 13, 42, 18, 806801), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 13, 42, 18, 807583), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('c273b1cc-8d7a-40fc-a9a8-410f72e2264d')),
        ),
    ]
