# Generated by Django 2.0.2 on 2018-02-09 20:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20180209_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenotification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitenotification',
            name='user',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 42, 19, 519426), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('13e60070-2ca7-4374-8288-8a7ee3ee2864')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 42, 19, 520848), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 42, 19, 521784), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('c8283495-06fe-45f4-9af2-fc76cec67d0e')),
        ),
    ]
