# Generated by Django 2.0.2 on 2018-02-09 23:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20180209_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitenotification',
            old_name='message',
            new_name='type',
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='other_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='sitenotification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 9863), verbose_name='notification created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 36, 974791), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a50cc25-ccbe-4d2c-9052-a578d7c31cdb')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 7868), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 8936), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('efe92dba-2c54-4ebf-99a5-c2225c506a5c')),
        ),
    ]
