# Generated by Django 2.0.2 on 2018-02-09 23:46

import datetime
from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20180209_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitenotification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sitenotification',
            name='other_user',
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='data',
            field=jsonfield.fields.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='sitenotification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 46, 25, 503663), verbose_name='notification created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 46, 25, 499680), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c61aa278-7f41-41af-85c0-30d70418245d')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 46, 25, 501605), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 46, 25, 502800), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('da3138aa-a71a-4de6-bfcd-5c481f60c0bd')),
        ),
    ]
