# Generated by Django 2.0.2 on 2018-02-11 21:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20180209_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='reset_confirmation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitenotification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 51, 22, 568544), verbose_name='notification created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 51, 22, 566135), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('dc27fc53-0935-445b-8896-12283a3687f3')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 51, 22, 567399), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 51, 22, 567963), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('13303815-c3dc-4efc-9c08-319d97fc71d2')),
        ),
    ]
