# Generated by Django 2.0 on 2018-02-22 03:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20180211_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenotification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 22, 48, 21, 221843), verbose_name='notification created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 22, 48, 21, 220834), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('606c6e03-719b-439d-9c57-bf430238b155')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 22, 48, 21, 221340), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 22, 48, 21, 221340), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('08bb61d9-311b-4d6f-85a9-f8745e5dea13')),
        ),
    ]
