# Generated by Django 2.0 on 2018-03-26 08:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20180222_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='sitenotification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 46408), verbose_name='notification created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 45402), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('660f111d-05b7-4132-8fcf-19b661a0f57f')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 45906), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 45906), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('12fbe402-f722-49dc-aec2-c98bf73d26bb')),
        ),
    ]
