# Generated by Django 2.0 on 2018-04-04 18:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20180326_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenotification',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 552205), verbose_name='notification created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 551203), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9332bca4-8d39-463c-94d8-5f7b76a582be')),
        ),
        migrations.AlterField(
            model_name='siteuserban',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 551704), verbose_name='date expired'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 551704), verbose_name='log created'),
        ),
        migrations.AlterField(
            model_name='siteuserlog',
            name='user',
            field=models.UUIDField(default=uuid.UUID('8204bcf5-9c74-49d0-b1c7-03efa9d9057f')),
        ),
    ]
