# Generated by Django 2.0.2 on 2018-02-07 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=8192)),
                ('creator', models.UUIDField()),
                ('status', models.CharField(choices=[('a', 'Under Review'), ('b', 'Awaiting Interview'), ('c', 'Accepted'), ('d', 'Denied')], max_length=1)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2018, 2, 7, 18, 31, 8, 32144), verbose_name='date published')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2018, 2, 7, 18, 31, 8, 32205), verbose_name='date updated')),
            ],
        ),
    ]
