# Generated by Django 2.0.2 on 2018-02-08 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapplication',
            name='content',
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='about_yourself',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='activity',
            field=models.CharField(choices=[('a', 'A couple hours every other day'), ('b', '1-2 hours a day'), ('c', '2-4 hours a day'), ('d', '4-8 hours a day')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='cheating_opinion',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='first_name',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='languages_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='languages_french',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='languages_german',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='languages_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='languages_spanish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='previous_experience',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='region',
            field=models.CharField(choices=[('a', 'NA'), ('b', 'EU'), ('c', 'SA'), ('d', 'AU'), ('e', 'Other(s)')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='telegram',
            field=models.TextField(default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 2, 44, 11, 171512), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='status',
            field=models.CharField(choices=[('a', 'Under Review'), ('b', 'Awaiting Interview'), ('c', 'Accepted'), ('d', 'Denied')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 2, 44, 11, 171544), verbose_name='date updated'),
        ),
    ]
