# Generated by Django 2.0.2 on 2018-02-09 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0004_auto_20180209_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 40, 55, 205229), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 40, 55, 205278), verbose_name='date updated'),
        ),
    ]
