# Generated by Django 2.0.2 on 2018-02-09 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0005_auto_20180209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 36457), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 36510), verbose_name='date updated'),
        ),
    ]
