# Generated by Django 2.0.2 on 2018-02-11 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0007_auto_20180209_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 51, 22, 582480), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 16, 51, 22, 582506), verbose_name='date updated'),
        ),
    ]
