# Generated by Django 2.0 on 2018-02-22 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0008_auto_20180211_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 22, 48, 21, 304538), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 21, 22, 48, 21, 304538), verbose_name='date updated'),
        ),
    ]
