# Generated by Django 2.0 on 2018-02-22 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0009_auto_20180221_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 0, 0, 55, 748436), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 0, 0, 55, 748436), verbose_name='date updated'),
        ),
    ]
