# Generated by Django 2.0 on 2018-03-26 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_apps', '0010_auto_20180222_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapplication',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 56907), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='region',
            field=models.CharField(choices=[('a', 'NA'), ('b', 'EU'), ('c', 'SA'), ('d', 'AS'), ('e', 'Other(s)')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 56907), verbose_name='date updated'),
        ),
    ]
