# Generated by Django 2.0 on 2018-01-27 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('traffic_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date checked')),
                ('proxy_id', models.TextField()),
                ('proxy_count', models.IntegerField()),
            ],
        ),
    ]
