# Generated by Django 2.0 on 2018-03-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkTraffic',
        ),
    ]
