# Generated by Django 2.0 on 2018-01-27 08:05

import datetime
from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_title', models.CharField(max_length=200)),
                ('ticket_content', django_markdown.models.MarkdownField(max_length=5000)),
                ('ticket_creator', models.UUIDField()),
                ('ticket_status', models.CharField(choices=[('a', 'Open'), ('b', 'Solved'), ('c', 'Closed'), ('d', 'Creator Replied'), ('e', 'Operator Replied')], max_length=1)),
                ('ticket_type', models.CharField(choices=[('a', 'Punishment Appeal'), ('b', 'Report Player'), ('c', 'Store Issues / Questions')], max_length=1)),
                ('ticket_handler', models.UUIDField(null=True)),
                ('ticket_publish_date', models.DateTimeField(default=datetime.datetime(2018, 1, 27, 3, 5, 56, 261922), verbose_name='date published')),
                ('ticket_updated_date', models.DateTimeField(default=datetime.datetime(2018, 1, 27, 3, 5, 56, 261922), verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBlacklistEntry',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('ticket_id', models.IntegerField()),
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', django_markdown.models.MarkdownField(max_length=5000)),
                ('reply_creator', models.UUIDField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2018, 1, 27, 3, 5, 56, 262423), verbose_name='date published')),
            ],
        ),
    ]
