# Generated by Django 2.0 on 2018-01-28 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 21, 38, 6, 80083), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 21, 38, 6, 80083), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 21, 38, 6, 80584), verbose_name='date published'),
        ),
    ]
