# Generated by Django 2.0 on 2018-01-28 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20180127_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 1, 18, 38, 565440), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 1, 18, 38, 565440), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 1, 18, 38, 565941), verbose_name='date published'),
        ),
    ]
