# Generated by Django 2.0 on 2018-01-28 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20180128_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 4, 26, 6, 654662), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 4, 26, 6, 654662), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 4, 26, 6, 655164), verbose_name='date published'),
        ),
    ]
