# Generated by Django 2.0 on 2018-01-28 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20180128_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 4, 27, 51, 29150), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 4, 27, 51, 29150), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 4, 27, 51, 29651), verbose_name='date published'),
        ),
    ]
