# Generated by Django 2.0 on 2018-01-28 12:38

import datetime
from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20180128_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='_ticket_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='_reply_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 7, 38, 36, 909548), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 7, 38, 36, 909548), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 7, 38, 36, 910049), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='reply_content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
