# Generated by Django 2.0 on 2018-01-28 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20180128_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_publish_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_updated_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 17, 29, 52, 601924), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 17, 29, 52, 601924), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 17, 29, 52, 602425), verbose_name='date published'),
        ),
    ]
