# Generated by Django 2.0.2 on 2018-02-08 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20180207_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 2, 44, 11, 168787), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 2, 44, 11, 168815), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 2, 44, 11, 169727), verbose_name='date published'),
        ),
    ]
