# Generated by Django 2.0.2 on 2018-02-09 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_auto_20180209_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 42, 19, 552376), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 42, 19, 552435), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 42, 19, 554304), verbose_name='date published'),
        ),
    ]
