# Generated by Django 2.0.2 on 2018-02-09 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_auto_20180209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 32101), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 32161), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 39, 37, 33445), verbose_name='date published'),
        ),
    ]
