# Generated by Django 2.0 on 2018-03-26 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0026_auto_20180222_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 54902), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 55431), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 4, 58, 5, 55931), verbose_name='date published'),
        ),
    ]
