# Generated by Django 2.0 on 2018-04-04 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_auto_20180326_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 567770), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 567770), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 14, 12, 53, 568274), verbose_name='date published'),
        ),
    ]
