# Generated by Django 2.0 on 2018-01-23 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=200)),
                ('requires_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('category_id', models.IntegerField()),
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_title', models.CharField(max_length=200)),
                ('forum_description', models.CharField(max_length=200)),
                ('requires_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('thread_id', models.IntegerField()),
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', django_markdown.models.MarkdownField()),
                ('reply_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('forum_id', models.IntegerField()),
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('thread_title', models.CharField(max_length=200)),
                ('thread_content', django_markdown.models.MarkdownField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date updated')),
                ('bumped_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date bumped')),
                ('thread_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
