# Generated by Django 2.0 on 2018-01-24 03:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20180123_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='requires_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forum',
            name='requires_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='thread',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('4c0a9ef8-6f3a-4602-a9d4-2da846dcdbd9')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('18226252-be25-46ac-8d9c-7a7eccd56731')),
        ),
    ]
