# Generated by Django 2.0 on 2018-01-25 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20180123_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='forum_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('b0bdf96e-8a40-4d16-b239-80ee26b83893')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('acf0fd6c-4cc4-4d61-9de9-8a95e66d04a1')),
        ),
    ]
