# Generated by Django 2.0 on 2018-01-27 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20180124_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('2489a0e0-f8fc-4975-a6fb-bcdf1da9325c')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('43809053-0dcf-43ff-8ae1-64b1ab69ed3a')),
        ),
    ]
