# Generated by Django 2.0 on 2018-01-28 02:38

from django.db import migrations, models
import precise_bbcode.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20180127_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='_reply_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='_thread_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('92b0d057-3e7a-46e6-8227-b408d1a46b62')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('287220b6-0972-4c8d-ba52-94f2bb1dbae7')),
        ),
    ]
