# Generated by Django 2.0 on 2018-01-28 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20180127_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='requires_admin',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='requires_staff',
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('78e9ba9c-009d-4192-a143-85927b5d9169')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('abb98a58-d900-444f-8bb5-9d1d74f71043')),
        ),
    ]
