# Generated by Django 2.0 on 2018-01-28 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20180128_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='requires_staff',
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('2d77f622-04cb-4e78-a8c7-40a8c1804197')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('6fe03f74-c9c8-436a-88f0-0540b4f7b4a6')),
        ),
    ]
