# Generated by Django 2.0 on 2018-01-28 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_auto_20180128_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='requires_admin',
        ),
        migrations.AddField(
            model_name='forum',
            name='requires_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('4f315ec3-f440-491e-aba9-59377c696623')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('4ea545bf-7961-4f55-8429-5669cb6229dd')),
        ),
    ]
