# Generated by Django 2.0 on 2018-01-28 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_auto_20180128_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('24b36b18-1517-40cb-9893-b50d08122e3e')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('961f9638-26d8-43a4-935b-64d2220417e6')),
        ),
    ]
