# Generated by Django 2.0 on 2018-01-28 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_auto_20180128_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('45fa3341-bc32-4107-825c-02bbbc0a37d9')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('e86a9d7b-16e0-4d84-afea-c4dfa6470824')),
        ),
    ]
