# Generated by Django 2.0 on 2018-01-30 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_auto_20180128_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='stickied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('91c45a89-5b3a-4adb-8a4b-a0575206494f')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('1ecd4164-a6cb-4320-aa1b-639682ab0a7d')),
        ),
    ]
