# Generated by Django 2.0 on 2018-02-07 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_auto_20180130_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('4ddee0ae-e420-4fe6-92b5-62de7de0c876')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('beff295f-7b01-47a4-b46f-0f5476cbb1b7')),
        ),
    ]
