# Generated by Django 2.0 on 2018-02-07 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_auto_20180206_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('bcffa1bb-bd2d-499f-a824-5b32bf929345')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('66d7e534-fa57-4d26-99bd-9ce8b9409cbe')),
        ),
    ]
