# Generated by Django 2.0 on 2018-02-07 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_auto_20180206_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('4c6a2b4b-0207-4d5e-addd-843146404cdc')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('9b6c74f6-e78f-42dd-b225-d10e5878cc92')),
        ),
    ]
