# Generated by Django 2.0 on 2018-02-07 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_auto_20180206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('48751d78-cff5-413e-affd-4ecddc59f59e')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('0b4bc313-1f74-4d3e-b0d0-379bec694f8e')),
        ),
    ]
