# Generated by Django 2.0 on 2018-02-07 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_auto_20180206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('9542cbbb-4660-41b5-8518-b6be85094884')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('79c604a8-ce44-431f-b262-5140abe788a0')),
        ),
    ]
