# Generated by Django 2.0 on 2018-02-07 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0017_auto_20180206_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('07435e9b-1a79-4a98-ba83-46b39485fc69')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('477ade00-a8c6-44b9-a72b-8d5440818baa')),
        ),
    ]
