# Generated by Django 2.0 on 2018-02-07 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_auto_20180206_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('57917dc5-a189-48c2-b1db-dfe3c70dede5')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('221dd23e-9cff-45a5-873e-f990d4891962')),
        ),
    ]
