# Generated by Django 2.0 on 2018-02-07 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0019_auto_20180206_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('fbecf2d2-f6e0-4f6b-a54d-077a80fcde51')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('c47b793b-ff40-437d-9eb2-eb0b1286621e')),
        ),
    ]
