# Generated by Django 2.0.2 on 2018-02-07 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_auto_20180206_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('4abc8ae2-9cb8-43c6-a703-a107d18eeb48')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('de8bb09e-c45d-4116-87b5-beece28345c8')),
        ),
    ]
