# Generated by Django 2.0.2 on 2018-02-08 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0021_auto_20180207_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('6e0bbc85-ec27-46f6-8fc8-cadb84ea7c4a')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('3afe627c-4232-4515-a884-4f5abaf5f853')),
        ),
    ]
