# Generated by Django 2.0.2 on 2018-02-09 18:42

from django.db import migrations, models
import precise_bbcode.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0022_auto_20180208_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=precise_bbcode.fields.BBCodeTextField(max_length=8192, no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('fa0a24c4-781a-48cc-93aa-e4bf34bf27ab')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_content',
            field=precise_bbcode.fields.BBCodeTextField(max_length=8192, no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('6d3de816-3dc1-42e4-ab2f-e53bf3398cab')),
        ),
    ]
