# Generated by Django 2.0.2 on 2018-02-09 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_auto_20180209_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('d2f64274-eed3-4db4-a2b1-33e82e65d41c')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('de26219d-6c5a-4a3b-9dc0-b5d7ce03b650')),
        ),
    ]
