# Generated by Django 2.0.2 on 2018-02-09 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_auto_20180209_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('1491f308-10e5-4de5-80fe-7989f8dfb785')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('8bd9f835-c276-421e-8529-f2761b6fa313')),
        ),
    ]
