# Generated by Django 2.0.2 on 2018-02-09 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0025_auto_20180209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('fc0f2ce3-5984-43c8-8942-97daf87256f6')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('1fa93378-fdcc-4cb1-a706-48b4f23dbf6c')),
        ),
    ]
