# Generated by Django 2.0.2 on 2018-02-09 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0026_auto_20180209_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('359bbc0b-71f5-490e-b4b3-8955dc06c12b')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('a86cb896-0e3e-46b9-baef-dbf450095668')),
        ),
    ]
