# Generated by Django 2.0.2 on 2018-02-11 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0027_auto_20180209_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('b5ad0d0e-1a29-485e-b35b-d18b5dfcdc93')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('7d3f0683-8545-4763-a7b0-f3899bcf55a8')),
        ),
    ]
