# Generated by Django 2.0 on 2018-02-22 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0028_auto_20180211_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('711ad202-988f-4126-bd0c-8eadfe2a1f0b')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('5a538d3c-44e1-4d2b-bfd0-b5ce442ee672')),
        ),
    ]
