# Generated by Django 2.0 on 2018-02-22 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0029_auto_20180221_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('5bfcab13-5ca3-496c-9082-ad6e1605a0c4')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('1447ced0-ab80-4d5a-bbd1-5c104f1fc31b')),
        ),
    ]
