# Generated by Django 2.0 on 2018-03-26 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0030_auto_20180222_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('4376ecbd-4786-4cfa-9106-9400c26598a9')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('86d87bdf-bf60-4b25-beed-9dd819c3e344')),
        ),
    ]
