# Generated by Django 2.0 on 2018-04-04 18:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0031_auto_20180326_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.TextField()),
                ('reply_creator', models.UUIDField(default=uuid.UUID('b0a4f60f-81bd-4bc9-a38b-e7ee6cb25b75'))),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date liked')),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('35db21dd-b470-4330-a485-42c9786f0e56')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('6e5244cc-a888-4d4f-9b82-5a9ef53c9e8e')),
        ),
    ]
