# Generated by Django 2.0 on 2018-04-04 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0032_auto_20180404_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('68a641bf-18a9-4c35-a914-b7ee71568555')),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_creator',
            field=models.UUIDField(default=uuid.UUID('b8a5b810-cd80-4b54-bf9b-18be2a1429fc')),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_creator',
            field=models.UUIDField(default=uuid.UUID('1d52c962-146f-4f2e-a276-181845278189')),
        ),
    ]
